name: release

on:
  push:
    branches:
      - "main"
    tags:
      - "v*.*.*"
env:
  REGISTRY: ghcr.io
  REGISTRY_IMAGE: ghcr.io/marthydavid/supermicro-letsencrypt


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5.7.0
        with:
          images: ${{ env.REGISTRY_IMAGE }}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern=v{{version}}
            type=semver,pattern=v{{major}}.{{minor}}
            type=semver,pattern=v{{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0

      - name: Login to Docker Hub
        uses: docker/login-action@v3.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6.17.0
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          provenance: false
          sbom: false

#      - name: Scan for vulnerabilities
#        id: scan
#        uses: crazy-max/ghaction-container-scan@v2
#        with:
#          image: ${{ steps.meta.outputs.tags }}
#          dockerfile: ./Dockerfile
#          
#      - name: Upload SARIF file
#        if: ${{ steps.scan.outputs.sarif != '' }}
#        uses: github/codeql-action/upload-sarif@v2
#        with:
#          sarif_file: ${{ steps.scan.outputs.sarif }}